### ISSUE TITLE
Hows the result compare with cam++

### ISSUE THREAD

**Issue by MonolithFoundation** [BUTSpeechFIT/DiaPer#10]
Hi, can u provide some suggestions on compare with cam++, this is currently the sota I known

**Comment by fnlandini** [comment]
Hi, do you mean [CAM++: A Fast and Efficient Network for Speaker Verification Using Context-Aware Masking](https://arxiv.org/pdf/2303.00332)? That is a model for speaker verification, not diarization so it would not be possible to compare to this system. In order to use CAM++ for diarization, you could extract speaker embeddings on short segments of speech and then cluster them to obtain speaker clusters that denote speaker diarization.
Regarding SOTA results for speaker verification, maybe you should take a look at [Reshape Dimensions Network for Speaker Recognition](https://arxiv.org/pdf/2407.18223) where they recently reported quite strong results.
I hope this helps

**Comment by MonolithFoundation** [comment]
@fnlandini  Yes, am I getting it wrong? I thought DiaPer also extracts embedding for clustering.

If not, does DiaPer able to segment extremly long audio length such as 4 hour? (more than 20 speakers)

**Comment by fnlandini** [comment]
@MonolithFoundation 
DiaPer does not do clustering, just end-to-end diarization. Some of the models shared here can find up to 10 speakers but not more. This is because it was not trained with more, but the model could be trained with data with more speakers and eventually handle more complex scenarios. However, I think that would be quite expensive from a training perspective. Also, while it can work on long files, it will consume a lot of memory.

If you want to run a clustering-based approach, you could try https://github.com/BUTSpeechFIT/VBx which we released a few years ago. It will not be the best model out there but still should provide reasonable outputs.

Or, you could try our recent https://github.com/BUTSpeechFIT/DiariZen which does end-to-end diarization in short segments and then clustering to be able to handle many speakers and very long recordings. If you are after that scenario, I recommend it. 

I hope this helps

**Comment by MonolithFoundation** [comment]
@fnlandini  Hi, many thanks for the useful information. I still have 2 questions want to consult:

1. It solves only 10 speaks if trained with according data, or any <= 10 speaks also can resolve? If not, the application is very stricted I think. Since many cases you can't sure that there is 10 speaks speaking;
2. Dia on a realatively short segments, and then clustering is a reasonable way, however, compare with method you mentioned previously such as RedimNet, is DiaZen better? ( in real-world scenarios)

**Comment by fnlandini** [comment]
Glad it helped.
1. The models trained with up to 10 speakers can find up to 10 speakers (i.e. 1, 2, etc.). However, the model will probably work better if there are fewer than 10 (for example less than 7). This is mainly because the model was trained with roughly equal amount of data with each number of speakers 1 to 10 and having very many speakers is a more challenging problem. For you to get an idea, if you check Figure 9.d (page 11) [here](https://arxiv.org/pdf/2312.04324) you can see how accurately the model finds the right number of speakers when presented with 1, 2, ..., 10. 

2.  Well, ReDimNet does not do diarization itself. You would need to run voice activity detection, extract embeddings and cluster them (how you do the clustering can have a big influence in the results). But even if you do that, this approach will not handle overlaps. If your recordings have often overlapping segments between speakers, a method that runs end-to-end diarization (like DiariZen) will be much better. But even more, DiariZen uses an embedding extractor in the clustering step (following pyannote) and that embedding extractor could be replaced by ReDimNet to improve the performance further.

**Comment by MonolithFoundation** [comment]
I hard to run DiaPer or DiariZen e2e, (given an audio, outputs speaker id and timetstmaps direclty), am a littile bit confused how DiaPar works on:

1. How did it solves overlaps? Outputs timestmaps with overlapping? Even tougth, ASR would hardly recognise it. 
2. Why does DiariZen needs embeeding extractor when it can handles overlaps? (i mean it should also be an e2e method right?)

**Comment by fnlandini** [comment]
Hi,
Maybe it makes sense for you to look at an output like [this one](https://github.com/BUTSpeechFIT/DiaPer/blob/main/results/DiaPer/10attractors/DIHARD2/withFT/eval/rttms/DH_0001.rttm)
The rttm files are a standard format for diarization outputs where each line represents a segment where the 4th column is the start time of the segment and the 5th column is the length of the segment. Then, the 8th column is the speaker label. Note that the speaker labels are not speaker identifiers but rather some label to distinguish the speakers in that specific recording.

This [script](https://github.com/BUTSpeechFIT/DiaPer/blob/main/run_example.sh) might be helpful to run a model on one file. You need to update the paths. Understanding what [infer_single_file.py](https://github.com/BUTSpeechFIT/DiaPer/blob/main/diaper/infer_single_file.py) does should be simple.

1. These approaches model each speaker separately. You can imagine the output like a matrix of size `speakers` times `length of the recording`. At each time, more than one speaker can be active, therefore overlapping each other. The final output is generated based on that matrix. Diarization is independent of ASR. If you want to combine the outputs of diarization and ASR models you will have to handle the labels of both systems somehow. You'll find some approaches if you search. ASR models struggle with overlaps but that is a limitation of the technology. Ideally, we would like models that can cope with that.
2. DiariZen runs the end-to-end in short segments. If you have a long recording and you run independently an end-to-end model, later you will need to stitch those decisions across the short segments. I think this [paper](https://www.isca-archive.org/interspeech_2023/bredin23_interspeech.pdf) will help you understand how it works.

**Comment by MonolithFoundation** [comment]
Thank u for the answer. Looks like DiaPer actually outputs labels directly, while other models such as cam++, RedimNet etc, needs extract embeddings and clustering them to get label id. (Correct me if am wrong).

So that, am wonder, if there any robust postprocessing lib to stitch short segments togather outputs from Diaper?
Also, how long does it suggested for each short segment to process to getting a most best result?

**Comment by fnlandini** [comment]
Yes, you are correct.

There is this [paper](https://www.isca-archive.org/iberspeech_2024/alvareztrejos24_iberspeech.pdf) where there is an analysis on how to stitch the decisions. Their evaluation data could also have many speakers and very long recordings so perhaps it matches your scenario. There is a tradeoff between short-enough segments so that DiaPer works better and the number of speakers is bounded versus having longer segments so that the embeddings used for stitching are more robust. You can explore segments of 1 or 2 minutes and then try eventually a bit longer too.

Regarding the stitching, DiariZen has that, following pyannote recipe. I think those would be the most straight-forward available recipes to do the stitching.

**Comment by MonolithFoundation** [comment]
thanks for the reply.

Where could I found the stitching part in Diazen? is that possible connncet with Diaper?

**Comment by fnlandini** [comment]
I think this is the [function](https://github.com/BUTSpeechFIT/DiariZen/blob/35f174f92b2be92c0b58e09fb48efb3144a34766/pyannote-audio/pyannote/audio/pipelines/speaker_diarization.py#L424) that does it.
Everything is possible, you will just need to code it :)

**Comment by MonolithFoundation** [comment]
Thanks, why there no one make a e2e workable pipeline on long audio, I think DiaPer is very promising to defeat some models widely used now such as cam++.

Am not profession on this area, if someone could have a lib to call, that would be very valuable.

**Comment by fnlandini** [comment]
To be honest, I do not remember having seen cam++ in any publication. Of course I am not aware if any companies have diarization solutions based on that. 
A library would be useful but it implies a certain amount of work that is not priority for this publication. 
Given that the original question was answered, I will close this issue.
Feel free to reopen if you have any comparison between the methods

**Comment by MonolithFoundation** [comment]
Hi, funasr have in their pipelines.
